build.gradle
=> [feat#4] JWT dependencies 추가

src/main/java/friend/spring/apiPayload/code/status/ErrorStatus.java, src/main/java/friend/spring/apiPayload/handler/AlarmHandler.java, src/main/java/friend/spring/converter/AlarmConverter.java, src/main/java/friend/spring/converter/UserConverter.java, src/main/java/friend/spring/repository/AlarmRepository.java, src/main/java/friend/spring/service/AlarmService.java, src/main/java/friend/spring/service/AlarmServiceImpl.java, src/main/java/friend/spring/web/controller/AlarmRestController.java, src/main/java/friend/spring/web/controller/UserRestController.java, src/main/java/friend/spring/web/dto/AlarmResponseDTO.java, src/main/java/friend/spring/web/dto/UserResponseDTO.java
=> # 51 알림 API 구현

src/main/java/friend/spring/converter/PostConverter.java, src/main/java/friend/spring/service/CommentService.java, src/main/java/friend/spring/service/CommentServiceImpl.java, src/main/java/friend/spring/service/PostService.java, src/main/java/friend/spring/service/PostServiceImpl.java, src/main/java/friend/spring/web/controller/CommentRestController.java, src/main/java/friend/spring/web/controller/PostRestController.java
=> #67 Refactor: 로그인 토큰으로 변경해서 적용

src/main/java/friend/spring/web/controller/UserRestController.java
User 관련 기능에서 swagger ApiResponses, parameter도 조금 작성한 건데 그냥 날리기가 아까워서 올립니다,,
=> #80 Refactor: User 관련 기능 swagger 간단 설명 작성

src/main/java/friend/spring/converter/CommentConverter.java, src/main/java/friend/spring/web/dto/CommentResponseDTO.java
댓글 조회 시 삭제된 댓글인지 여부를 나타내도록 추가했습니다!
=> #29 Refactor: 댓글 조회 시 상태 추가

src/main/java/friend/spring/apiPayload/code/status/ErrorStatus.java, src/main/java/friend/spring/security/JwtTokenProvider.java
토큰 유효 시간 수정, 카카오 관련 errorStatus 추가, 카카오 로그인은 진행중
=> Feat#71 토큰 유효 시간 수정

src/main/java/friend/spring/repository/CommentRepository.java, src/main/java/friend/spring/service/CommentService.java, src/main/java/friend/spring/service/CommentServiceImpl.java, src/main/java/friend/spring/web/controller/CommentRestController.java
프론트에서 연동하실 때 
댓글 조회에서 page 처리를 제거하면 좋겠다고 해주셔서 제거했습니다!
=> Feat#29 Refactor: 댓글 조회 page 처리 제거

src/main/java/friend/spring/domain/User.java, src/main/java/friend/spring/repository/CommentRepository.java, src/main/java/friend/spring/service/CommentService.java, src/main/java/friend/spring/service/CommentServiceImpl.java, src/main/java/friend/spring/service/MyPageService.java, src/main/java/friend/spring/service/MyPageServiceImpl.java, src/main/java/friend/spring/service/PostServiceImpl.java, src/main/java/friend/spring/web/controller/CommentRestController.java, src/main/java/friend/spring/web/controller/MyPageRestController.java
전에도 리뷰 글 제외하고 조회하도록 설정했었는데
지난번에 실행했을 때 뭔가 에러가 났어서,,
확실히 제외해보았습니다,,
+) 회원정보 수정(사용자 프로필 사진) 기능 추가도 그냥 이 브랜치에 일단 포함해서 올렸습니다..!!
=> Feat#55 홈 - 답변을 기다리는 고민들 조회 시 리뷰 글 제외

src/main/java/friend/spring/converter/MyPageConverter.java, src/main/java/friend/spring/domain/User.java, src/main/java/friend/spring/service/MyPageService.java, src/main/java/friend/spring/service/MyPageServiceImpl.java, src/main/java/friend/spring/web/controller/MyPageRestController.java, src/main/java/friend/spring/web/dto/MyPageRequestDTO.java, src/main/java/friend/spring/web/dto/MyPageResponseDTO.java
상우님께서 구현하신 이메일 인증 코드 전송을 누른뒤 받은 인증 코드와 비교하는 방식으로 API 구현했습니다!
=> Feat#106 회원정보 수정(이름 변경, 이메일 변경) API 구현

src/main/java/friend/spring/converter/CommentConverter.java, src/main/java/friend/spring/service/CommentService.java, src/main/java/friend/spring/service/CommentServiceImpl.java, src/main/java/friend/spring/web/controller/CommentRestController.java, src/main/java/friend/spring/web/dto/CommentResponseDTO.java
=> #108 Refactor: 댓글 조회 시 좋아요/글 주인/내가 쓴 댓글 여부 추가 & 댓글 삭제 api url에서 like 제거

src/main/java/friend/spring/service/CommentServiceImpl.java
대댓글의 대댓글을 null이 아니라 빈 ArrayList로 보내도록 바꾸었습니다!
=> #108 Refactor: 대댓글 목록 수정

src/main/java/friend/spring/domain/File.java, src/main/java/friend/spring/repository/FileRepository.java, src/main/java/friend/spring/service/MyPageServiceImpl.java, src/main/java/friend/spring/service/S3Service.java, src/main/java/friend/spring/web/controller/MyPageRestController.java
이슈 브랜치와 관련은 없지만,, 
유저 프로필 사진 수정하는 부분에서 
유저 프로필 사진이 이미 있는 경우에 
기존 데이터에서 이미지 url 링크만 변경으로 수정했습니다!
=> #113 Refactor: 유저 프로필 사진 이미 있는 경우 수정으로 변경

src/main/java/friend/spring/converter/MyPageConverter.java, src/main/java/friend/spring/domain/Inquiry.java, src/main/java/friend/spring/domain/User.java, src/main/java/friend/spring/domain/enums/InquiryCategory.java, src/main/java/friend/spring/domain/enums/RoleType.java, src/main/java/friend/spring/repository/InquiryRepository.java, src/main/java/friend/spring/service/MyPageService.java, src/main/java/friend/spring/service/MyPageServiceImpl.java, src/main/java/friend/spring/web/controller/MyPageRestController.java, src/main/java/friend/spring/web/dto/MyPageRequestDTO.java, src/main/java/friend/spring/web/dto/MyPageResponseDTO.java
=> #123 Feat : 회원정보 수정(보안 메일 변경) API 구현, Inquiry테이블 생성, 문의하기 API 구현

src/main/java/friend/spring/repository/PostRepository.java
원래 24시간 이내 글들 중 조회였는데, 데모데이까지 임시로 7일 이내로 수정하겠습니다!
=> #113 Refactor: 가장 핫한 고민투표 임시로 7일 이내로 수정

src/main/java/friend/spring/service/EmailService.java, src/main/java/friend/spring/service/PasswordEmailService.java, src/main/java/friend/spring/web/controller/UserRestController.java, src/main/java/friend/spring/web/dto/UserRequestDTO.java
=> 비밀번호 재설정 메일인증 API

src/main/java/friend/spring/converter/SseConverter.java
=> #113 Refactor: 알림 타입 변경

src/main/java/friend/spring/web/controller/AlarmRestController.java
간단한 수정이어서 리뷰 요청 없이 merge하겠습니다!
=> #113 Refactor: 홈 - 안 읽은 알림 존재 여부 조회 설명 수정

src/main/java/friend/spring/converter/PostConverter.java, src/main/java/friend/spring/web/dto/PollOptionDTO.java
간단한 수정이어서 리뷰 요청 없이 merge하겠습니다!
=> #147 Refactor: 글 상세보기 시 후보 아이디도 반환으로 수정

src/main/java/friend/spring/service/CommentServiceImpl.java
간단한 수정이어서 리뷰 요청 없이 merge하겠습니다!
=> #147 Refactor: 댓글 상세보기 대댓글 관련 수정

src/main/java/friend/spring/converter/CandidateConverter.java, src/main/java/friend/spring/converter/PostConverter.java, src/main/java/friend/spring/repository/PostRepository.java, src/main/java/friend/spring/service/PostService.java, src/main/java/friend/spring/service/PostServiceImpl.java, src/main/java/friend/spring/web/controller/PostRestController.java, src/main/java/friend/spring/web/dto/CandidateResponseDTO.java, src/main/java/friend/spring/web/dto/PostResponseDTO.java
이전에 제가 만든 리턴 값 이용하려고 했었는데 
그냥 주훈님 고민글 전체 보기 방식을 그대로 참고해서 이용했습니다,,
감사합니다,,👍
=> #146 Refactor: 홈 - 답변을 기다리는 고민들 / 홈 - 지금 가장 핫한 고민투표 리턴 값 수정

src/main/java/friend/spring/converter/CommentConverter.java, src/main/java/friend/spring/repository/CommentChoiceRepository.java, src/main/java/friend/spring/service/CommentServiceImpl.java, src/main/java/friend/spring/web/dto/CommentResponseDTO.java
간단한 수정이어서 리뷰 요청 없이 merge하겠습니다!
=> #155 Refactor: 댓글 조회 시 채택 여부도 리턴

src/main/java/friend/spring/service/PostServiceImpl.java, src/main/java/friend/spring/service/VoteServiceImpl.java
간단한 수정이라서 리뷰 요청 없이 merge하겠습니다!
=> #155 Refactor: 투표/글 작성 시 포인트 amount 값 수정

src/main/java/friend/spring/apiPayload/code/status/ErrorStatus.java, src/main/java/friend/spring/converter/UserConverter.java, src/main/java/friend/spring/security/JwtTokenProvider.java, src/main/java/friend/spring/service/EmailService.java, src/main/java/friend/spring/service/UserService.java, src/main/java/friend/spring/service/UserServiceImpl.java, src/main/java/friend/spring/web/controller/UserRestController.java, src/main/java/friend/spring/web/dto/UserRequestDTO.java, src/main/java/friend/spring/web/dto/UserResponseDTO.java
accessToken 48시간으로 수정
비밀번호 재설정 완료
=> [REFACTOR] 비밀번호 재설정 완료, accessToken 시간 수정

src/main/java/friend/spring/converter/PostConverter.java, src/main/java/friend/spring/repository/CommentRepository.java, src/main/java/friend/spring/service/SchedulerService2.java
투표 마감 전에도 allCandidatePercent 값을 null 이 아니라 리스트로 보내달라고 하셔서 수정합니다!
=> #155 Refactor: 일반/카드 투표 allCandidatePercent 리스트 리턴으로 수정

src/main/java/friend/spring/converter/Base64Decoder.java, src/main/java/friend/spring/service/PostService.java, src/main/java/friend/spring/service/PostServiceImpl.java, src/main/java/friend/spring/service/S3Service.java, src/main/java/friend/spring/web/controller/PostRestController.java, src/main/java/friend/spring/web/dto/CandidateRequestDTO.java, src/main/java/friend/spring/web/dto/PostRequestDTO.java
프론트분들께서 글 작성 / 후보 생성 시 이미지 올릴 때 
MultipartFile -> Base64로 수정해달라고 하셔서 수정했습니다!
=> #155 Refactor: 이미지 파일 업로드 방식 MultipartFile -> Base64로 수정

src/main/java/friend/spring/web/controller/PostRestController.java
하핳 제가 잘못 설정했네욜,,,^^
[Thanks To]
- 지민님 해결해주셔서 감사해요,,
- 민경님 응원 감사해요
- 주훈님 봐주셔서 감사해요
- 고민친구 짱,, FOREVER,,,
=> #155 Refactor: 글 작성에서 MULTIPART_FORM_DATA_VALUE 추가

.platform/nginx.conf
=> #155 Refactor: Nginx 설정 proxy_read_timeout 값 1시간으로 수정 (테스트)

.platform/nginx.conf
=> #155 Refactor: Nginx 설정 proxy_connet, send timeout 값 1시간으로 수정 (테스트)

.platform/nginx.conf
=> #155 Refactor: Nginx 설정 connection 추가

.platform/nginx.conf
=> #155 Refactor: Nginx 설정 chunked_transfer_encoding off; 추가

.platform/nginx/nginx.conf
=> #155 Refactor: nginx 설정에서 timeout 설정만 남기고 제거 (테스트)

src/main/java/friend/spring/config/CorsConfig.java
=> #155 Refactor: cors 설정에서 allowedOriginPatterns("*") 제거해보기 (테스트)

src/main/java/friend/spring/config/CorsConfig.java
=> #155 Refactor: cors 설정에서 .allowedOrigins("*") 제거 (테스트)

.platform/nginx/nginx.conf, src/main/java/friend/spring/config/CorsConfig.java
=> Feat#155 Refactor: nginx.conf cors 설정 추가, Access-Control-Allow-Credential 'true' 추가

src/main/java/friend/spring/config/CorsConfig.java
=> #155 Refactor: nginx.conf cors 설정 제거, CorsConfig에 .allowCredentials(true) 추가

src/main/java/friend/spring/converter/UserConverter.java, src/main/java/friend/spring/domain/User.java, src/main/java/friend/spring/service/UserService.java, src/main/java/friend/spring/service/UserServiceImpl.java, src/main/java/friend/spring/web/controller/UserRestController.java, src/main/java/friend/spring/web/dto/UserRequestDTO.java, src/main/resources/application.yml
=> [REFACTOR] 비밀번호 재설정 리턴값 수정

src/main/java/friend/spring/repository/PostRepository.java, src/main/java/friend/spring/service/PostServiceImpl.java
#193 이슈
24시간 (지금은 임시로 일주일 이내)에 올라온 투표글 중에
- 투표 마감이 안 되었고
- 내가 투표 참여 안 한
- 투표글들을 투표 수 적은 순으로 30개 뽑아서 랜덤으로 섞어서 보여주기
로 수정합니다!
=> Feat#193 Refactor: 답변을 기다리는 고민들 로직 수정
